name: Build and Test Otlichnik

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        platform: [ubuntu-22.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r otlichnik/requirements.txt
          pip install -r otlichnik/dev-requirements.txt
          pip install -e otlichnik
      - name: Test with pytest
        run: |
          cd otlichnik
          pytest